name: ipycytoscape_docs
channels:
 - conda-forge
dependencies:
 - python=3.6
 - ipycytoscape=1.0.3
 - sphinx
 - sphinx_rtd_theme
 - sphinx-autobuild
 - jupyter-sphinx>=0.3.1
 - sphinx-copybutton
 - nbsphinx
 - pip
 - pip:
    - nbsphinx_link
