name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: lint javascript
        shell: bash -l {0}
        run: |
          npm install
          npm run lint-check
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install with dependencies
        shell: bash -l {0}
        run: pip install -e ".[test]"
      - name: lint python
        shell: bash -l {0}
        run: |
          black --check ipycytoscape setup.py docs/source/conf.py
          flake8 ipycytoscape setup.py docs/source/conf.py
