name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip nodejs jupyter jupyterlab black

    - name: Install ipycytoscape
      shell: bash -l {0}
      run: pip install -e ".[test, examples]"

    # For build speed only means using one of the runs for the long step
    # Nothing is special about 3.7. That should be bumped when the python
    # versions that are tested are bumped.
    - name: Install labextension (Only on 3.7 for build speed)
      if: matrix.python-version == 3.7
      shell: bash -l {0}
      run: |
        jupyter labextension install . 
        jupyter labextension list 1>labextensions 2>&1
        cat labextensions | grep "jupyter-cytoscape.*OK"
        python -m jupyterlab.browser_check
        
    - name: Run Tests
      shell: bash -l {0}
      run: pytest . --color=yes
